In [14]:
import pandas as pd
data = {
    "age": [20, 22, 21, None, 24, 23, 25, 22, 26, 24,
            27, 21, 23, 25, 28, 26, 29, 24, 27, 30],

    "salary": [25000, 32000, 28000, 45000, None, 38000, 52000, 30000, 60000, 41000,
               65000, 27000, 35000, None, 72000, 58000, 80000, 43000, 68000, 85000],

    "gender": ["Male", "Female", "Male", "Female", None, "Male", "Female", "Male", "Female", "Male",
               "Female", "Male", "Female", "Male", "Female", "Male", "Female", "Male", "Female", "Male"],

    "city": ["Kolkata", "Delhi", "Patna", "Kolkata", "Mumbai", "Delhi", "Patna", "Kolkata", "Delhi", "Mumbai",
             "Patna", "Kolkata", "Delhi", "Mumbai", "Patna", "Kolkata", "Delhi", "Mumbai", "Patna", "Kolkata"],

    "result": ["Pass", "Fail", "Pass", "Pass", "Fail", "Pass", "Pass", "Fail", "Pass", "Pass",
               "Pass", "Fail", "Pass", "Pass", "Pass", "Fail", "Pass", "Pass", "Fail", "Pass"]
}

df = pd.DataFrame(data)
df

     age   salary  gender     city result
0   20.0  25000.0    Male  Kolkata   Pass
1   22.0  32000.0  Female    Delhi   Fail
2   21.0  28000.0    Male    Patna   Pass
3    NaN  45000.0  Female  Kolkata   Pass
4   24.0      NaN    None   Mumbai   Fail
5   23.0  38000.0    Male    Delhi   Pass
6   25.0  52000.0  Female    Patna   Pass
7   22.0  30000.0    Male  Kolkata   Fail
8   26.0  60000.0  Female    Delhi   Pass
9   24.0  41000.0    Male   Mumbai   Pass
10  27.0  65000.0  Female    Patna   Pass
11  21.0  27000.0    Male  Kolkata   Fail
12  23.0  35000.0  Female    Delhi   Pass
13  25.0      NaN    Male   Mumbai   Pass
14  28.0  72000.0  Female    Patna   Pass
15  26.0  58000.0    Male  Kolkata   Fail
16  29.0  80000.0  Female    Delhi   Pass
17  24.0  43000.0    Male   Mumbai   Pass
18  27.0  68000.0  Female    Patna   Fail
19  30.0  85000.0    Male  Kolkata   Pass

In [15]:
df.shape

(20, 5)

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   age     19 non-null     float64
 1   salary  18 non-null     float64
 2   gender  19 non-null     object
 3   city    20 non-null     object
 4   result  20 non-null     object
dtypes: float64(2), object(3)
memory usage: 932.0+ bytes

In [17]:
df.isna().sum()

age       1
salary    2
gender    1
city      0
result    0
dtype: int64

In [18]:
# missing values percentage
(df.isna().sum()/len(df))*100

age        5.0
salary    10.0
gender     5.0
city       0.0
result     0.0
dtype: float64

In [19]:
# fill numerical missing values with median
df['age'] = df['age'].fillna(df['age'].median())

In [20]:
# fill numerical missing values with median
df['salary'] = df['salary'].fillna(df['salary'].median())

In [23]:
# fill categorical missing values with mode
df['gender'] = df['gender'].fillna(df['gender'].mode()[0])

In [24]:
# verify
df.isna().sum()

age       0
salary    0
gender    0
city      0
result    0
dtype: int64

In [25]:
df.duplicated().sum()

np.int64(0)

In [26]:
X = df[["age", "salary", "gender", "city"]]
y = df["result"]

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

(4, 4)

In [30]:
# One-hot Encoding 
X_train = pd.get_dummies(
    X_train, columns=["gender", "city"],
    dtype=int
)

X_test = pd.get_dummies(
    X_test, columns=["gender", "city"],
    dtype=int
)

In [31]:
X_train.head()

,age,salary,gender_Female,gender_Male,city_Delhi,city_Kolkata,city_Mumbai,city_Patna
8,26.0,60000.0,1,0,1,0,0,0
5,23.0,38000.0,0,1,1,0,0,0
11,21.0,27000.0,0,1,0,1,0,0
3,24.0,45000.0,1,0,0,1,0,0
18,27.0,68000.0,1,0,0,0,0,1

In [33]:
X_train, X_test = X_train.align(
    X_test, join="left",axis=1, fill_value=0
)

In [34]:
X_test.head()

,age,salary,gender_Female,gender_Male,city_Delhi,city_Kolkata,city_Mumbai,city_Patna
0,20.0,25000.0,0,1,0,1,0,0
17,24.0,43000.0,0,1,0,0,1,0
15,26.0,58000.0,0,1,0,1,0,0
1,22.0,32000.0,1,0,1,0,0,0

In [36]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [37]:
X_train_scaled[:5]

array([[ 0.40350576,  0.50569007,  1.        , -1.        ,  1.73205081,
        -0.57735027, -0.48038446, -0.67419986],
       [-0.73580463, -0.7135079 , -1.        ,  1.        ,  1.73205081,
        -0.57735027, -0.48038446, -0.67419986],
       [-1.49534489, -1.32310689, -1.        ,  1.        , -0.57735027,
         1.73205081, -0.48038446, -0.67419986],
       [-0.3560345 , -0.32558128,  1.        , -1.        , -0.57735027,
         1.73205081, -0.48038446, -0.67419986],
       [ 0.78327589,  0.94903478,  1.        , -1.        , -0.57735027,
        -0.57735027, -0.48038446,  1.4832397 ]])

In [38]:
X_train_scaled_df = pd.DataFrame(
    X_train_scaled, columns=X_train.columns
)
X_train_scaled_df.head()

,age,salary,gender_Female,gender_Male,city_Delhi,city_Kolkata,city_Mumbai,city_Patna
0,0.403506,0.505690,1.0,-1.0,1.732051,-0.577350,-0.480384,-0.67420
1,-0.735805,-0.713508,-1.0,1.0,1.732051,-0.577350,-0.480384,-0.67420
2,-1.495345,-1.323107,-1.0,1.0,-0.577350,1.732051,-0.480384,-0.67420
3,-0.356034,-0.325581,1.0,-1.0,-0.577350,1.732051,-0.480384,-0.67420
4,0.783276,0.949035,1.0,-1.0,-0.577350,-0.577350,-0.480384,1.48324

In [39]:
X_train_scaled_df.mean()

age              0.000000e+00
salary           1.387779e-17
gender_Female    0.000000e+00
gender_Male      0.000000e+00
city_Delhi      -5.551115e-17
city_Kolkata    -5.551115e-17
city_Mumbai     -1.387779e-17
city_Patna       5.551115e-17
dtype: float64

In [40]:
X_train_scaled_df.std()

age              1.032796
salary           1.032796
gender_Female    1.032796
gender_Male      1.032796
city_Delhi       1.032796
city_Kolkata     1.032796
city_Mumbai      1.032796
city_Patna       1.032796
dtype: float64

In [41]:
df.isna().sum()

age       0
salary    0
gender    0
city      0
result    0
dtype: int64

In [46]:
df.head()

    age   salary  gender     city result
0  20.0  25000.0    Male  Kolkata   Pass
1  22.0  32000.0  Female    Delhi   Fail
2  21.0  28000.0    Male    Patna   Pass
3  24.0  45000.0  Female  Kolkata   Pass
4  24.0  44000.0    Male   Mumbai   Fail